spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/park?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
